INSERT INTO tb_category (name, created_At) VALUES ('Notebooks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drawing Tablets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mices', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mousepads', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Flash Drives', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Headsets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Webcams', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('No-Breaks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Keyboards', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smartwatches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kindles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Video Projectors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Data Storages', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Monitors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Scanners', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Printers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hubs', NOW());
